version: '3'
services:
  web:
    image: bobcamera/bob-web-prod:1.2.7
    #user: ${MY_UID}:${MY_GID}
    build: 
      context: .
      target: bob-web-prod
    ports:
      - "8080:80"
  # If you want to view demo recordings, comment out the volume section below.      
    volumes: 
      - ${PWD}/assets/recordings:/var/www/html/videos
    depends_on:
      - bob
  bob:
    image: bobcamera/bob-ros2-prod:1.2.7
    #user: ${MY_UID}:${MY_GID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      target: bob-ros2-prod    
    ports:
      - "9090:9090"
    environment:  # add in .env
      - BOB_SOURCE=${BOB_SOURCE}
      - BOB_RTSP_URL=${BOB_RTSP_URL}
      - BOB_CAMERA_ID=${BOB_CAMERA_ID}
      - BOB_ENABLE_VISUALISER=${BOB_ENABLE_VISUALISER}
      - BOB_ENABLE_RECORDING=${BOB_ENABLE_RECORDING}
      - BOB_BGS_ALGORITHM=${BOB_BGS_ALGORITHM}
      - BOB_TRACKING_SENSITIVITY=${BOB_TRACKING_SENSITIVITY}
      - BOB_TRACKING_USEMASK=${BOB_TRACKING_USEMASK}
      - BOB_TRACKING_MASK_FILE=${BOB_TRACKING_MASK_FILE}
      - BOB_VIDEOS=${BOB_VIDEOS}
      - BOB_SIMULATION_NUM_OBJECTS=${BOB_SIMULATION_NUM_OBJECTS}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
      - FASTRTPS_DEFAULT_PROFILES_FILE=${FASTRTPS_DEFAULT_PROFILES_FILE}
    volumes: 
      - ${PWD}/assets/:/workspaces/bobcamera/src/ros2/assets/
      - ${PWD}/media:/workspaces/bobcamera/media
  # If you want to use a usb camera uncomment the devices comment below
  #  devices:
  #    - /dev/video0:/dev/video0 
  # cron:
  #   image: ghcr.io/bobcamera/bob-crontab
  #   #privileged: true
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   build:
  #     context: .
  #     target: bob-crontab
  #   #user: "${UID}:${GID}"
  #   volumes: 
  #     - ${PWD}/assets/:/bob-research/assets/

volumes:
  assets:
    driver: local
