
#docker buildx build --progress=plain --push --platform linux/amd64 -f ./docker/Dockerfile-base-dev . -t bobcamera/bob-base-cuda:1.5.8 -t bobcamera/bob-base-cuda:latest --target base-cuda

#FROM ubuntu:noble
FROM nvidia/cuda:12.5.1-devel-ubuntu24.04 AS base-cuda

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS_DISTRO jazzy

# setup timezone and install packages
RUN echo 'Etc/UTC' > /etc/timezone \
    && ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime \
    && apt-get update &&  apt-get upgrade \
    && apt-get install -q -y --no-install-recommends tzdata dirmngr gnupg2 \
    rm -rf /var/lib/apt/lists/*

# setup keys and setup sources.list
RUN set -eux; \
       key='C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654'; \
       export GNUPGHOME="$(mktemp -d)"; \
       gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
       mkdir -p /usr/share/keyrings; \
       gpg --batch --export "$key" > /usr/share/keyrings/ros2-latest-archive-keyring.gpg; \
       gpgconf --kill all; \
       rm -rf "$GNUPGHOME" \
    && echo "deb [ signed-by=/usr/share/keyrings/ros2-latest-archive-keyring.gpg ] http://packages.ros.org/ros2/ubuntu noble main" > /etc/apt/sources.list.d/ros2-latest.list

# install ros2 packages and install bootstrap tools
RUN apt-get update && apt-get install -y --no-install-recommends \
      ros-jazzy-ros-core=0.11.0-1* \
      build-essential \
      git \
      python3-colcon-common-extensions \
      python3-colcon-mixin \
      python3-rosdep \
      python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep and setup colcon mixin and metadata
RUN rosdep init && \
  rosdep update --rosdistro $ROS_DISTRO \
  && colcon mixin add default \
      https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update && \
    colcon metadata add default \
      https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml && \
    colcon metadata update

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-jazzy-ros-base=0.11.0-1* \
    && rm -rf /var/lib/apt/lists/*