# Kernel
rstp_camera_node:
  ros__parameters:
    rtsp_uri:
    image_topic:
    image_width:
    image_height:
    camera_calibration_file:

rstp_overlay_camera_node:
  ros__parameters:
    rtsp_uri:
    image_topic:
    image_width:
    image_height:
    camera_calibration_file:

web_camera_video_node:
  ros__parameters:
    image_publish_topic:
    image_info_publish_topic:
    camera_info_publish_topic:
    is_video:
    videos:
    resize_height:

usb_camera_node:
  ros__parameters:
    image_publish_topic:
    image_info_publish_topic:
    camera_info_publish_topic:
    is_video:
    videos:
    resize_height:

simulated_frame_provider_node:
  ros__parameters:
    height:
    width:
    num_objects:

web_camera_video_overlay_node:
  ros__parameters:
    image_publish_topic:
    image_info_publish_topic:
    camera_info_publish_topic:
    is_video:
    videos:
    resize_height:

simulation_overlay_provider_node:
  ros__parameters:
    height:
    width:
    num_objects:

mask_application_node:
  ros__parameters:
    mask_file:

minimal_background_subtractor_node:
  ros__parameters:
    bgs:
    vibe_params:
    wmv_params:
    blob_params:
    use_mask:

low_background_subtractor_node:
  ros__parameters:
    bgs:
    vibe_params:
    wmv_params:
    blob_params:
    use_mask:

medium_background_subtractor_node:
  ros__parameters:
    bgs:
    vibe_params:
    wmv_params:
    blob_params:
    use_mask:

high_background_subtractor_node:
  ros__parameters:
    bgs:
    vibe_params:
    wmv_params:
    blob_params:
    use_mask:

allsky_recorder_node:
  ros__parameters:
    video_directory:
    img_topic:
    tracking_topic:
    prefix:
    codec:
    video_fps:
    seconds_save:

foreground_mask_recorder_node:
  ros__parameters:
    video_directory:
    img_topic:
    tracking_topic:
    prefix:
    codec:
    video_fps:
    seconds_save:

bayer_frame_resizer_node:
  ros__parameters:
    resize_height:

foreground_mask_frame_resizer_node:
  ros__parameters:
    resize_height:

annotated_frame_resizer_node:
  ros__parameters:
    resize_height:

# Display
multi_frame_viewer_node:
  ros__parameters:
    topics:

single_frame_viewer_node:
  ros__parameters:
    topics:

annotated_frame_compressor_node:
  ros__parameters:
    compression_quality:

bayer_compressor_node:
  ros__parameters:
    compression_quality:

# Monitoring infrastructure
day_night_classifier_node:
  ros__parameters:
    observer_timer_interval: 
    observer_day_night_brightness_threshold:

cloud_estimator_node:
  ros__parameters:
    observer_timer_interval:

tracking_monitor_node:
  ros__parameters:
    observer_tracker_monitor_busy_interval:
    observer_tracker_monitor_idle_interval:
    observer_tracking_profile_busy_switch_threshold:
    observer_tracker_sample_set:

prometheus_metrics_node:
  ros__parameters:
    port: 8082

# Web infrastructure
mask_webapi_node:
  ros__parameters:
    masks_folder: 'assets/masks'
    width:
    height:
