# Kernel
rtsp_camera_node:
  ros__parameters:
    rtsp_uri: ''
    onvif_host: ''
    onvif_port: 0
    onvif_user: ''
    onvif_password: ''        
    image_publish_topic: 'bob/frames/allsky/original'
    image_info_publish_topic: 'bob/camera/all_sky/image_info'
    camera_info_publish_topic: 'bob/camera/all_sky/camera_info'
    source_type: 'RTSP_STREAM'
    image_width: 0
    image_height: 0
    camera_calibration_file: 'file:///workspaces/bobcamera/src/ros2/assets/config/camera_info.yaml'

rtsp_overlay_camera_node:
  ros__parameters:
    rtsp_uri: ''
    onvif_host: ''
    onvif_port: 0
    onvif_user: ''
    onvif_password: ''
    image_publish_topic: 'bob/simulation/input_frame'
    image_info_publish_topic: 'bob/camera/all_sky/image_info'
    camera_info_publish_topic: 'bob/camera/all_sky/camera_info'
    source_type: 'RTSP_STREAM'
    image_width: 0
    image_height: 0
    camera_calibration_file: 'file:///workspaces/bobcamera/src/ros2/assets/config/camera_info.yaml'

web_camera_video_node:
  ros__parameters:
    image_publish_topic: 'bob/frames/allsky/original'
    image_info_publish_topic: 'bob/camera/all_sky/image_info'
    camera_info_publish_topic: 'bob/camera/all_sky/camera_info'
    source_type: 'VIDEO_FILE'
    videos:
    resize_height: 0

usb_camera_node:
  ros__parameters:
    image_publish_topic: 'bob/frames/allsky/original'
    image_info_publish_topic: 'bob/camera/all_sky/image_info'
    camera_info_publish_topic: 'bob/camera/all_sky/camera_info'
    source_type: 'USB_CAMERA'
    camera_id: 0
    resize_height: 0

simulated_frame_provider_node:
  ros__parameters:
    height: 0
    width: 0
    num_objects: 0

web_camera_video_overlay_node:
  ros__parameters:
    image_publish_topic: 'bob/simulation/input_frame'
    image_info_publish_topic: 'bob/camera/all_sky/image_info'
    camera_info_publish_topic: 'bob/camera/all_sky/camera_info'
    source_type: 'VIDEO_FILE'
    videos:
    resize_height: 0

simulation_overlay_provider_node:
  ros__parameters:
    height: 0
    width: 0
    num_objects: 0
    video_fps: 10.0

detection_mask_application_node:
  ros__parameters:
    mask_file: 'assets/masks/detection-mask.jpg'
    mask_enable_override: True
    mask_enable_offset_correction: True
    image_width: 0
    image_height: 0    

privacy_mask_application_node:
  ros__parameters:
    mask_file: 'assets/masks/privacy-mask.jpg'
    mask_enable_override: True
    mask_enable_offset_correction: False
    image_width: 0
    image_height: 0    

background_subtractor_v2_node:
  ros__parameters:
    sensitivity: 'medium_c'
    bgs: ''
    json_params: '[
                    {
                      "name": "low",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 55, "bgSamples": 32, "requiredBGSamples": 1, "learningRate": 8
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 45.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 8, "areaThreshold": 64, "minDistance": 64, "maxBlobs": 50
                        }, 
                        "median_filter": false 
                      }
                    },
                    {
                      "name": "medium",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 40, "bgSamples": 32, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 30.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 4, "areaThreshold": 16, "minDistance": 16, "maxBlobs": 50
                        }, 
                        "median_filter": false 
                      }
                    },
                    {
                      "name": "high",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 30, "bgSamples": 16, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 15.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 2, "areaThreshold": 4, "minDistance": 4, "maxBlobs": 50
                        }, 
                        "median_filter": false 
                      }
                    },    
                    {
                      "name": "low_c",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 55, "bgSamples": 32, "requiredBGSamples": 1, "learningRate": 8
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 45.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 8, "areaThreshold": 64, "minDistance": 64, "maxBlobs": 50
                        }, 
                        "median_filter": true 
                      }
                    },
                    {
                      "name": "medium_c",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 40, "bgSamples": 16, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 20.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 2, "areaThreshold": 4, "minDistance": 4, "maxBlobs": 50
                        }, 
                        "median_filter": true 
                      }
                    },
                    {
                      "name": "high_c",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 25, "bgSamples": 16, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 15.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 2, "areaThreshold": 4, "minDistance": 4, "maxBlobs": 50
                        }, 
                        "median_filter": true 
                      }
                    }
                  ]'

track_provider_node:
  ros__parameters:
    pass: True

allsky_recorder_node:
  ros__parameters:
    recordings_directory: 'assets/recordings'
    img_topic: 'bob/frames/allsky/masked/privacy'
    fg_img_topic: 'bob/frames/foreground_mask'
    tracking_topic: 'bob/tracker/tracking'
    camera_info_topic: bob/camera/all_sky/camera_info
    prefix: ''
    codec: 'avc1'
    video_fps: 15.0
    seconds_save: 2
    #pipeline: 'appsrc ! videoconvert ! openh264enc bitrate=10240000 qp-min=10 qp-max=51 ! h264parse ! mp4mux ! filesink location='

annotated_frame_provider_node:
  ros__parameters:
    tracking_status_message: False

detection_masked_frame_resizer_node:
  ros__parameters:
    resize_height: 960

privacy_masked_frame_resizer_node:
  ros__parameters:
    resize_height: 960

foreground_mask_frame_resizer_node:
  ros__parameters:
    resize_height: 960

annotated_frame_resizer_node:
  ros__parameters:
    resize_height: 960

# Display
multi_frame_viewer_node:
  ros__parameters:
    topics: 
      - 'bob/frames/annotated/resized'
      - 'bob/frames/foreground_mask/resized'
      - 'bob/frames/allsky/masked/detection/resized'
      - 'bob/frames/allsky/masked/privacy/resized'

annotated_frame_compressor_node:
  ros__parameters:
    compression_quality: 95

detection_masked_compressor_node:
  ros__parameters:
    compression_quality: 95

privacy_masked_compressor_node:
  ros__parameters:
    compression_quality: 95

foreground_mask_compressor_node:
  ros__parameters:
    compression_quality: 95

# Monitoring infrastructure
day_night_classifier_node:
  ros__parameters:
    observer_timer_interval: 90
    observer_day_night_brightness_threshold: 95

cloud_estimator_node:
  ros__parameters:
    observer_timer_interval: 90

monitoring_status_aggregator_node:
  ros__parameters:
    observer_tracker_monitor_busy_interval: 5
    observer_tracker_monitor_idle_interval: 60
    observer_tracker_aggregation_interval: 1
    observer_tracking_profile_busy_switch_threshold: 5
    observer_tracker_sample_set: 5

track_sensitivity_monitor_node:
  ros__parameters:
    check_interval: 30
    sensitivity: 'medium_c'

config_manager_node:
  ros__parameters:
    pass: True

prometheus_metrics_node:
  ros__parameters:
    port: 8082

onvif_service_node:
  ros__parameters:
    onvif_wsdl_path: 'assets/wsdl'

# Web infrastructure
info_webapi_node:
  ros__parameters:
    application_version: '1.2.13'
    frame_width: 0
    frame_height: 0
    video_fps: 15.0

mask_webapi_node:
  ros__parameters:
    masks_folder: ''
    width: 0
    height: 0
