launch:
  node_containers:
    - name: Kernel
      nodes:
        - package: bob_camera
          plugin: CameraBGS
          name: camera_node
          remappings: []
        - package: bob_tracking
          plugin: TrackProvider
          name: track_provider_node
          remappings: []
        - package: bob_recorder
          plugin: RecordManager
          name: allsky_recorder_node
          remappings: []
        - package: bob_image_processing
          plugin: AnnotatedFrameProvider
          name: annotated_frame_provider_node
          remappings: []
        - package: bob_image_processing
          plugin: FrameCompressor
          name: annotated_frame_compressor_node
          remappings:
            - 'bob/compressor/source': 'bob/frames/annotated/resized'
            - 'bob/compressor/target': 'bob/frames/annotated/resized/compressed'
        - package: bob_image_processing
          plugin: FrameCompressor
          name: detection_masked_compressor_node
          remappings:
            - 'bob/compressor/source': 'bob/frames/allsky/original/resized'
            - 'bob/compressor/target': 'bob/frames/allsky/original/resized/compressed'
        - package: bob_image_processing
          plugin: FrameCompressor
          name: foreground_mask_compressor_node
          remappings:
            - 'bob/compressor/source': 'bob/frames/foreground_mask/resized'
            - 'bob/compressor/target': 'bob/frames/foreground_mask/resized/compressed'
    - name: Display
      nodes:
        - package: bob_visualizers
          plugin: FrameViewer
          name: multi_frame_viewer_node
          remappings: []
    - name: Monitor
      nodes:
        - package: bob_image_processing
          plugin: TrackSensitivityMonitor
          name: track_sensitivity_monitor_node
          remappings: []
        - package: bob_recorder
          plugin: RecordingMonitor
          name: allsky_recorder_monitoring_node
          remappings: []
  nodes:
    - package: bob_observer
      executable: day_night_classifier
      name: day_night_classifier_node
      remappings:
        - 'bob/observer_frame/source': 'bob/frames/allsky/original/resized'
    - package: bob_observer
      executable: cloud_estimator
      name: cloud_estimator_node
      remappings:
        - 'bob/observer_frame/source': 'bob/frames/allsky/original/resized'
    - package: bob_observer
      executable: star_mask
      name: star_mask_node
      remappings:
        - 'bob/observer_frame/source': '/bob/frames/allsky/original/resized'
    - package: bob_monitor
      executable: monitoring_status_aggregator
      name: monitoring_status_aggregator_node
      remappings: []
    - package: bob_monitor
      executable: onvif_service
      name: onvif_service_node
      remappings: []

# Kernel
camera_node:
  ros__parameters:
    image_publish_topic: 'bob/frames/allsky/original'
    image_info_publish_topic: 'bob/camera/all_sky/image_info'
    camera_info_publish_topic: 'bob/camera/all_sky/camera_info'
    image_resized_publish_topic: 'bob/frames/allsky/original/resized'
    source_type: 'VIDEO_FILE'
    videos:
      - /workspaces/bobcamera/media/fisheye_videos/mike-drone.mp4
      - /workspaces/bobcamera/media/fisheye_videos/mikeg-30min.mp4
    resize_height: 960
    privacy_mask_file: 'assets/masks/privacy-mask.jpg'
    simulator_num_objects: 15
    simulator: True
    bgs_sensitivity: 'low_c'
    bgs_type: 'vibe'
    bgs_mask_file: 'assets/masks/detection-mask.jpg'
    bgs_json_params: '[
                    {
                      "name": "low",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 65, "bgSamples": 32, "requiredBGSamples": 1, "learningRate": 8
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 50.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 10, "areaThreshold": 100, "minDistance": 100, "maxBlobs": 25
                        }, 
                        "median_filter": false 
                      }
                    },
                    {
                      "name": "medium",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 45, "bgSamples": 32, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 30.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 6, "areaThreshold": 36, "minDistance": 36, "maxBlobs": 25
                        }, 
                        "median_filter": false 
                      }
                    },
                    {
                      "name": "high",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 30, "bgSamples": 16, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 15.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 4, "areaThreshold": 16, "minDistance": 16, "maxBlobs": 25
                        }, 
                        "median_filter": false 
                      }
                    },    
                    {
                      "name": "low_c",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 65, "bgSamples": 32, "requiredBGSamples": 1, "learningRate": 8
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 50.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 10, "areaThreshold": 100, "minDistance": 100, "maxBlobs": 25
                        }, 
                        "median_filter": true 
                      }
                    },
                    {
                      "name": "medium_c",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 45, "bgSamples": 16, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 25.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 6, "areaThreshold": 36, "minDistance": 36, "maxBlobs": 25
                        }, 
                        "median_filter": true 
                      }
                    },
                    {
                      "name": "high_c",
                      "sensitivity": {
                        "vibe": {
                          "threshold": 25, "bgSamples": 16, "requiredBGSamples": 1, "learningRate": 4
                        }, 
                        "wmv": {
                          "enableWeight": true, "enableThreshold": true, "threshold": 15.0, "weight1": 0.5, "weight2": 0.3, "weight3": 0.2
                        }, 
                        "blob": {
                          "sizeThreshold": 4, "areaThreshold": 16, "minDistance": 16, "maxBlobs": 25
                        }, 
                        "median_filter": true 
                      }
                    }
                  ]'

track_provider_node:
  ros__parameters:
    pass: True

allsky_recorder_node:
  ros__parameters:
    recordings_directory: 'assets/recordings'
    img_topic: 'bob/frames/allsky/original'
    fg_img_topic: 'bob/frames/foreground_mask'
    tracking_topic: 'bob/tracker/tracking'
    camera_info_topic: bob/camera/all_sky/camera_info
    prefix: ''
    codec: 'avc1'
    video_fps: 15.0
    seconds_save: 2
    #pipeline: 'appsrc ! videoconvert ! openh264enc bitrate=10240000 qp-min=10 qp-max=51 ! h264parse ! mp4mux ! filesink location='

annotated_frame_provider_node:
  ros__parameters:
    tracking_status_message: False
    image_resized_publish_topic: '/bob/frames/annotated/resized'

annotated_frame_compressor_node:
  ros__parameters:
    compression_quality: 75

detection_masked_compressor_node:
  ros__parameters:
    compression_quality: 75

privacy_masked_compressor_node:
  ros__parameters:
    compression_quality: 75

foreground_mask_compressor_node:
  ros__parameters:
    compression_quality: 75

# Display
multi_frame_viewer_node:
  ros__parameters:
    topics: 
      - '/bob/frames/annotated/resized/compressed'
      - '/bob/frames/allsky/original/resized/compressed'
      - '/bob/frames/allsky/original'
      - '/bob/frames/foreground_mask/resized'
      - '/bob/frames/foreground_mask'

# Monitoring infrastructure
day_night_classifier_node:
  ros__parameters:
    observer_timer_interval: 90
    observer_day_night_brightness_threshold: 95

cloud_estimator_node:
  ros__parameters:
    observer_timer_interval: 90

star_mask_node:
  ros__parameters:
    detection_mask_file: 'assets/masks/detection-mask.jpg'
    detection_mask_backup_file: 'assets/masks/detection-mask-backup.jpg'
    observer_timer_interval: 90
    observer_cross_correlation_threshold: 0.5

monitoring_status_aggregator_node:
  ros__parameters:
    observer_tracker_monitor_busy_interval: 5
    observer_tracker_monitor_idle_interval: 60
    observer_tracker_aggregation_interval: 1
    observer_tracking_profile_busy_switch_threshold: 5
    observer_tracker_sample_set: 5

track_sensitivity_monitor_node:
  ros__parameters:
    bgs_node: 'camera_node'
    check_interval: 10
    sensitivity_increase_count_threshold: 5
    sensitivity: 'medium_c'
    star_mask_enabled: True    

allsky_recorder_monitoring_node:
  ros__parameters:
    check_interval: 5

config_manager_node:
  ros__parameters:
    pass: True

prometheus_metrics_node:
  ros__parameters:
    port: 8082

onvif_service_node:
  ros__parameters:
    onvif_wsdl_path: 'assets/wsdl'

# Web infrastructure
info_webapi_node:
  ros__parameters:
    application_version: '1.3.1'
    frame_width: 0
    frame_height: 0
    video_fps: 15.0

mask_webapi_node:
  ros__parameters:
    masks_folder: ''
    width: 0
    height: 0
