ARG VARIANT=7.4
FROM mcr.microsoft.com/vscode/devcontainers/php:${VARIANT}
#RUN apt-get update && apt-get install ffmpeg
# FROM php:7.4-apache
# COPY ./src/ /var/www/html/
# COPY startup.sh /usr/local/bin/startup.sh
# RUN chmod +x /usr/local/bin/startup.sh
# CMD ["/usr/local/bin/startup.sh"]