ARG VARIANT=7.4
FROM mcr.microsoft.com/vscode/devcontainers/php:${VARIANT}
# FROM php:7.4-apache
# COPY ./src/ /var/www/html/
# COPY startup.sh /usr/local/bin/startup.sh
# RUN chmod +x /usr/local/bin/startup.sh
# CMD ["/usr/local/bin/startup.sh"]
